name: Update Police Data

on:
  workflow_dispatch:  # manuell ausl√∂sbar
  schedule:
    - cron: '*/1 * * * *' # optional: alle 1 Minute

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download police-data.json
        run: |
          curl -o assets/police-data.json http://45.93.250.210:25570/police-data.json

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/police-data.json
          git commit -m "Update police-data.json"
          git push https://${{ secrets.GH_PAT }}@github.com/TubaTankBoy/Polizeidrp-website.git HEAD:main || echo "Nothing to commit"
